/*
 * Copyright Captainsoft 2010 - 2015.
 * All rights reserved.
 */
package com.captainsoft.tools.patch.de;

import java.util.HashMap;
import java.util.Map;

import com.captainsoft.tools.patch.PatchData;

/**
 * @author
 */
public class ItemPatchGerman implements PatchData {

    public Map<String, String> data() {
        Map<String, String> p = new HashMap<String, String>();
        p.put("1", "Blume");
        p.put("2", "Blume");
        p.put("3", "Blume");
        p.put("4", "Teller");
        p.put("5", "Tasse");
        p.put("6", "Küchenmesser");
        p.put("7", "Tischdecke");
        p.put("8", "Tischdecke");
        p.put("9", "Kerze");
        p.put("10", "Kerze");
        p.put("11", "Erdbeeren");
        p.put("12", "Pizza Napoli");
        p.put("13", "Kirschen");
        p.put("14", "Banane");
        p.put("15", "Tafel Schokolade");
        p.put("16", "Nußecke");
        p.put("17", "Donut");
        p.put("18", "Dose Limo");
        p.put("19", "Packung Erdnüsse");
        p.put("20", "Tasse Milchkaffee");
        p.put("21", "Kanne Milchkaffee");
        p.put("22", "Mana-Müsli-Riegel");
        p.put("23", "Mana-Dauer-Lutsch-Bonbons");
        p.put("24", "Mana-Energy-Drink");
        p.put("25", "Kerze");
        p.put("26", "Tuch");
        p.put("27", "Kelch");
        p.put("28", "Kerzenständer");
        p.put("29", "Deckchen");
        p.put("30", "Gabel");
        p.put("31", "Schokoriegel");
        p.put("32", "Justin Chamberlain Püppchen");
        p.put("33", "kleine Statue");
        p.put("34", "Deep Dungeon T-Shirt");
        p.put("35", "Püppchen");
        p.put("36", "Püppchen");
        p.put("37", "wertvoller Kelch");
        p.put("38", "wertvolle Statue");
        p.put("39", "wertvolle Schale");
        p.put("40", "wertvolles Kreuz");
        p.put("41", "wertvolle Krone");
        p.put("42", "wertvoller Armreifen");
        p.put("43", "wertvolles Hufeisen");
        p.put("44", "Stoffetzen");
        p.put("45", "Dungeon Big Burger");
        p.put("46", "Müll");
        p.put("47", "Dose Müll");
        p.put("48", "Scherben");
        p.put("49", "Stoffetzen");
        p.put("50", "Wakizashi");
        p.put("51", "Degen");
        p.put("52", "Jagdschwert");
        p.put("53", "Breitschwert");
        p.put("54", "Piratensäbel");
        p.put("55", "Katana");
        p.put("56", "Claymore");
        p.put("57", "Stachelschwert");
        p.put("58", "Blitzschwert");
        p.put("59", "Spezial - Katana (+2)");
        p.put("60", "Schlangenschwert");
        p.put("61", "Rubinschwert");
        p.put("62", "Drachenschwert");
        p.put("63", "Totenkopfsäbel");
        p.put("64", "Schwert der Ronin");
        p.put("65", "Schwert der Shaolin");
        p.put("66", "Kampfstab");
        p.put("67", "Wunderkerzen");
        p.put("68", "Knüppel");
        p.put("69", "Kampfpaddel");
        p.put("70", "Speer");
        p.put("71", "Hellebarde");
        p.put("72", "Dreizack");
        p.put("73", "Schlangenspeer");
        p.put("74", "Spieß von Li Tai Peh");
        p.put("75", "Speer der Masai");
        p.put("76", "Wurfstacheln");
        p.put("77", "Kurzbogen");
        p.put("78", "Bumerang");
        p.put("79", "Armbrust");
        p.put("80", "Indianerbogen");
        p.put("81", "Ninja Sterne");
        p.put("82", "Doppelarmbrust");
        p.put("83", "Tigerbogen");
        p.put("84", "Geisterbogen");
        p.put("85", "Jadebogen");
        p.put("86", "Tomahawk");
        p.put("87", "Doppelaxt");
        p.put("88", "Streitaxt");
        p.put("89", "Axt der Wikinger");
        p.put("90", "Vollmondaxt");
        p.put("91", "Prismaschwert");
        p.put("92", "Knochenschwert");
        p.put("93", "Hörnerschwert");
        p.put("94", "Fez");
        p.put("95", "Zobelmütze");
        p.put("96", "Eisenhelm");
        p.put("97", "Taschko");
        p.put("98", "Chitinhelm");
        p.put("99", "Ritterhelm");
        p.put("100", "Löwenmaske");
        p.put("101", "Knochenhelm");
        p.put("102", "Helm von Matawaloo");
        p.put("103", "Helm der Unterwelt");
        p.put("104", "Trenchcoat");
        p.put("105", "Eisenpanzer");
        p.put("106", "Samuraiharnisch");
        p.put("107", "Chitinpanzer");
        p.put("108", "Ritterrüstung");
        p.put("109", "Löwenrüstung");
        p.put("110", "Knochenrüstung");
        p.put("111", "Uniform von Miyamato");
        p.put("112", "Rüstung der Unterwelt");
        p.put("113", "Jaderüstung");
        p.put("114", "Hose");
        p.put("115", "Eisenpanzer");
        p.put("116", "Samurairüstung");
        p.put("117", "Chitinrüstung");
        p.put("118", "Löwenhose");
        p.put("119", "Ritterrüstung");
        p.put("120", "Knochenrüstung");
        p.put("121", "Uniform von Chen Chen");
        p.put("122", "Rüstung der Unterwelt");
        p.put("123", "Jaderüstung");
        p.put("124", "Umhang der Unterwelt");
        p.put("125", "Tigerumhang");
        p.put("126", "Jadekette");
        p.put("127", "Jadeschild");
        p.put("128", "Fledermausumhang");
        p.put("129", "Kette von Moderam Soderam");
        p.put("130", "Samuraikette");
        p.put("131", "Schlangenkette");
        p.put("132", "Eisenschild");
        p.put("133", "Holzschild");
        p.put("134", "Chitinschild");
        p.put("135", "Jadeumhang");
        p.put("136", "Krawatte");
        p.put("137", "T-Shirt XXL");
        p.put("138", "Goldkette");
        p.put("139", "\"Mückenschwarm\"");
        p.put("140", "\"Prismageschoß\"");
        p.put("141", "\"Der Vorschlaghammer\"");
        p.put("142", "\"Meteorregen\"");
        p.put("143", "\"magischer Vampirbiß\"");
        p.put("144", "\"Zinnsoldaten greifen an\"");
        p.put("145", "\"Heißwachs Säuberung\"");
        p.put("146", "\"Hitze der Sahara\"");
        p.put("147", "\"Dampfwolke\"");
        p.put("148", "\"Bowling Penetration\"");
        p.put("149", "\"heiße Stern-Stacheln\"");
        p.put("150", "\"Wasser-Perlen\"");
        p.put("151", "\"Blitz\"");
        p.put("152", "\"Magnesiumstrahlen\"");
        p.put("153", "\"chinesisches Feuerwerk\"");
        p.put("154", "\"Atom Explosion\"");
        p.put("155", "\"Cholesterin-Vergiftung\"");
        p.put("156", "\"Regenschauer\"");
        p.put("157", "\"Hagelgewitter\"");
        p.put("158", "\"Schneelawine\"");
        p.put("159", "Shaolin-Pulver");
        p.put("160", "Schleim-Bombe");
        p.put("161", "Chinaböller");
        p.put("162", "Lava-Bombe");
        p.put("163", "Wassebombe");
        p.put("164", "Tomatensaft-Bombe");
        p.put("165", "Pfeffer-Bombe");
        p.put("166", "Stinkbombe");
        p.put("167", "Chili Kaffee");
        p.put("168", "\"Bunga Terra Tissa Tu\"");
        p.put("169", "\"Zaubersprüche\"");
        p.put("170", "\"Chemische Reaktionen\"");
        p.put("171", "\"Bomben und ihre Wirkung\"");
        p.put("172", "");
        p.put("173", "\"DeepDeep Dungeon Lösung\"");
        p.put("174", "\"Power Games\"");
        p.put("175", "");
        p.put("176", "Eimer");
        p.put("177", "Eimer voll mit Chili");
        p.put("178", "Stück Drath");
        p.put("179", "Instant-Kaffee");
        p.put("180", "schwerer Goldschmuck");
        p.put("181", "Spannungsmesser");
        p.put("182", "Lineal");
        p.put("183", "Schreibunterlage");
        p.put("184", "Büroklammer");
        p.put("185", "Bild");
        p.put("186", "Blume");
        p.put("187", "Blume");
        p.put("188", "Müll");
        p.put("189", "Füller");
        p.put("190", "Büroschlüssel");
        p.put("191", "diamatenbesetzer Helm");
        p.put("192", "");
        p.put("193", "Augäpfel von einem Zombie");
        p.put("194", "Bein von einem Zombie");
        p.put("195", "Arm von einem Zombie");
        p.put("196", "Arm von einem Zombie");
        p.put("197", "Bein von einem Zombie");
        p.put("198", "Auftragszettel");
        p.put("199", "Dungeonschlüssel");
        p.put("200", "Zimmerschlüssel");
        p.put("201", "Schaufel");
        p.put("202", "Schlüssel Boteneingang");
        p.put("203", "grüner Schlüssel");
        p.put("204", "Beweismittel");
        p.put("205", "schweres Gewicht");
        p.put("206", "Schlüssel zum Teleporter");
        p.put("207", "lila Schlüssel");
        p.put("208", "Schlüssel \"Experience\"");
        p.put("209", "Diamantenkette");
        p.put("210", "Goldketten");
        p.put("211", "Truhen-Dietrich");
        p.put("212", "Schraubenzieher");
        p.put("213", "gelber Schlüssel");
        p.put("214", "Zange");
        p.put("215", "Handtuch");
        p.put("216", "Regenbogen-Salzstreuer");
        p.put("217", "Kerze");
        p.put("218", "Fischgräte");
        p.put("219", "Hot Chili Dish");
        p.put("220", "Code-Wheel");
        p.put("221", "Ei von einem Emu");
        p.put("222", "Papier von einem Kaugummi");
        p.put("223", "Packung Kaugummi");
        p.put("224", "Transitvisum");
        p.put("225", "Bestellung von Bradfish");
        p.put("226", "Schlüssel von Ringring");
        p.put("227", "Nuko Comic");
        p.put("228", "Schlüssel von Wilbur");
        p.put("229", "Eintrittskarte");
        p.put("230", "Stuhlbein");
        p.put("231", "Studioschlüssel A");
        p.put("232", "Schlüssel zum innerem Dungeon");
        p.put("233", "Schlüssel vom Bungalow");
        p.put("234", "Zellenschlüsselbund");
        p.put("235", "Schlüssel vom Fan-Shop");
        p.put("236", "Bleimunition");
        p.put("237", "glitzernde Perlen");
        p.put("238", "Totenkopfschlüssel");
        p.put("239", "Quest-Request Nr.1");
        p.put("240", "Quest-Request Nr.2");
        p.put("241", "Quest-Request Nr.3");
        p.put("242", "Teleporterprisma");
        p.put("243", "Rote Keycard");
        p.put("244", "");
        p.put("245", "");
        p.put("246", "50 chips");
        p.put("247", "40 chips");
        p.put("248", "20 chips");
        p.put("249", "30 chips");
        p.put("250", "70 chips");
        return p;
    }

}
