/*
 * Copyright Captainsoft 2010 - 2015.
 * All rights reserved.
 */
package com.captainsoft.tools.patch.de;

import java.util.HashMap;
import java.util.Map;

import com.captainsoft.tools.patch.PatchData;

/**
 * @author
 */
public class MonsterPatchGerman implements PatchData {

    public Map<String, String> data() {
        Map<String, String> p = new HashMap<String, String>();
        p.put("1-n", "Auge auf zwei Beinen");
        p.put("1-a", "schlägt<X>mit seinem Glubschauge");
        p.put("2-n", "schleimiger Darmwurm");
        p.put("2-a", "bespuckt<X>mit schleimiger Spucke");
        p.put("3-n", "Brain Drainer (from Hell)");
        p.put("3-a", "schnappt nach<X>");
        p.put("4-n", "Teppich der Qualen");
        p.put("4-a", "beißt<X>");
        p.put("5-n", "Fliegendes Darm-Monster");
        p.put("5-a", "spritzt Magensäfte auf<X>");
        p.put("6-n", "Das böse T");
        p.put("6-a", "hämmert auf<X>'s Kopf");
        p.put("7-n", "Feuerspuckender Schlund");
        p.put("7-a", "spuckt Feuer gegen<X>");
        p.put("8-n", "Die agressive Wolke");
        p.put("8-a", "duscht<X>kalt");
        p.put("9-n", "Evil Spell");
        p.put("9-a", "verzaubert<X>");
        p.put("10-n", "Stomactract Masticator");
        p.put("10-a", "schnappt nach<X>");
        p.put("11-n", "Mad Jumper");
        p.put("11-a", "springt auf<X>");
        p.put("12-n", "Mister Bombastic");
        p.put("12-a", "rempelt sich gegen<X>");
        p.put("13-n", "Skelett Kämpfer");
        p.put("13-a", "schwing goldenen Säbel gegen<X>");
        p.put("14-n", "Magier der Feuerberge");
        p.put("14-a", "beschwört Feuerregen auf<X>");
        p.put("15-n", "Zipfelstein");
        p.put("15-a", "sticht<X>");
        p.put("16-n", "Stein Monster");
        p.put("16-a", "boxt<X>");
        p.put("17-n", "Stein Monster General");
        p.put("17-a", "boxt<X>feste");
        p.put("18-n", "GIGANTUS");
        p.put("18-a", "patscht<X>mit seinen Flossen");
        p.put("19-n", "Räuber");
        p.put("19-a", "überfällt<X>");
        p.put("20-n", "Menschenfressender Baum");
        p.put("20-a", "greift nach<X>mit seinen knöchrigen Ästen");
        p.put("21-n", "Magischer Baum");
        p.put("21-a", "verstreut Magiepollen gegen<X>");
        p.put("22-n", "Mohrrüber-Kerl");
        p.put("22-a", "knallt seine Rübe gegen<X>");
        p.put("23-n", "Kartoffelmonster");
        p.put("23-a", "stampft auf<X>herum");
        p.put("24-n", "Fleischfressende Pflanze");
        p.put("24-a", "schlingt sich um<X>");
        p.put("25-n", "Riesenmolch");
        p.put("25-a", "schlingt nach<X>mit seiner Zunge");
        p.put("26-n", "Saure Gurke");
        p.put("26-a", "blickt böse zu<X>");
        p.put("27-n", "Bergmonster");
        p.put("27-a", "greift mit seinen Klauen nach<X>");
        p.put("28-n", "Geier");
        p.put("28-a", "stürzt sich auf<X>");
        p.put("29-n", "Gewitterwolke");
        p.put("29-a", "wirft Blitze auf<X>");
        p.put("30-n", "Bösartiges Comicheft");
        p.put("30-a", "patscht<X>mit seinen Seiten");
        p.put("31-n", "Zauberer");
        p.put("31-a", "richtet seinen bösen Zauber gegen<X>");
        p.put("32-n", "Gespenst");
        p.put("32-a", "greift nach<X>");
        p.put("33-n", "Vampir");
        p.put("33-a", "beißt<X>");
        p.put("34-n", "Fledermaus");
        p.put("34-a", "stürzt sich auf<X>");
        p.put("35-n", "Erdwurm");
        p.put("35-a", "schnappt nach<X>");
        p.put("36-n", "Dunkler Wächter");
        p.put("36-a", "schwingt seine Axt nach<X>");
        p.put("37-n", "Prawn Pronk Monk");
        p.put("37-a", "greift mit seinen Tentakeln nach<X>");
        p.put("38-n", "Mutantor");
        p.put("38-a", "schnappt nach<X>");
        p.put("39-n", "Augenschwamm");
        p.put("39-a", "spritzt Säure gegen<X>");
        p.put("40-n", "Eisstern");
        p.put("40-a", "friert<X>ein");
        p.put("41-n", "Gnom aus Zürich");
        p.put("41-a", "wirft seinen Pickel nach<X>");
        p.put("42-n", "Modermensch");
        p.put("42-a", "stänkert gegen<X>");
        p.put("43-n", "Spinne");
        p.put("43-a", "beißt<X>");
        p.put("44-n", "Bodenschleim");
        p.put("44-a", "schleimt gegen<X>");
        p.put("45-n", "Geist");
        p.put("45-a", "erschreckt<X>");
        p.put("46-n", "Tentakel");
        p.put("46-a", "saugt an<X>");
        p.put("47-n", "Hörnerbock");
        p.put("47-a", "rempelt sich gegen<X>");
        p.put("48-n", "Dungeon Ratte");
        p.put("48-a", "beißt<X>");
        p.put("49-n", "Fire-Skull");
        p.put("49-a", "brät<X>");
        p.put("50-n", "Lip Lipp");
        p.put("50-a", "krallt sich<X>");
        p.put("51-n", "CANRABBONGO");
        p.put("51-a", "beißt<X>");
        p.put("52-n", "Magiegeschoss");
        p.put("52-a", "feuert Glitzer gegen<X>");
        p.put("53-n", "Skelett Krieger");
        p.put("53-a", "säbelt gegen<X>");
        p.put("54-n", "Feuermagier");
        p.put("54-a", "zaubert Feuerball auf<X>");
        p.put("55-n", "Riesendämon");
        p.put("55-a", "krallt sich<X>");
        p.put("56-n", "Recycl-Clohr");
        p.put("56-a", "schnappt nach<X>");
        p.put("57-n", "Killer Tomate");
        p.put("57-a", "matscht sich auf<X>");
        p.put("58-n", "Mumie");
        p.put("58-a", "greift nach<X>");
        p.put("59-n", "Dungeon Master");
        p.put("59-a", "stampft auf<X>");
        p.put("60-n", "Rheumaster");
        p.put("60-a", "zaubert Wassserfall auf<X>");
        p.put("61-n", "Rheuma Element");
        p.put("61-a", "erkältet<X>");
        p.put("62-n", "Tricktruhe");
        p.put("62-a", "schnappt nach<X>");
        p.put("63-n", "Drache");
        p.put("63-a", "speit Feuer auf<X>");
        p.put("64-n", "Skkizzor");
        p.put("64-a", "greift mit seinen Scheren nach<X>");
        p.put("65-n", "Beholder");
        p.put("65-a", "schnappt nach<X>");
        p.put("66-n", "Feuerteufel");
        p.put("66-a", "zündelt an<X>");
        p.put("67-n", "Riesen Tarantel");
        p.put("67-a", "beißt<X>");
        p.put("68-n", "Zombie");
        p.put("68-a", "schmeißt seine Gehirnmasse auf<X>");
        p.put("69-n", "Sabbernder Zombie");
        p.put("69-a", "sabbert auf<X>");
        p.put("70-n", "Zombie-Salesman");
        p.put("70-a", "greift nach<X>");
        p.put("71-n", "Zombie-Mutant");
        p.put("71-a", "beißt<X>");
        p.put("72-n", "Zombiewache");
        p.put("72-a", "schlägt auf<X>ein");
        p.put("73-n", "Zombie-Hausmeister");
        p.put("73-a", "prügelt mit seinem Mop auf<X>ein");
        p.put("74-n", "Fleischfressende Pflanze");
        p.put("74-a", "schlingt nach<X>");
        p.put("75-n", "Zombie-Sekretärin");
        p.put("75-a", "prügelt mit Büromaterialien auf<X>ein");
        p.put("76-n", "Feuerpilz");
        p.put("76-a", "macht sich heiß gegen<X>");
        p.put("77-n", "Schimmelpilz");
        p.put("77-a", "schimmelt gegen<X>");
        p.put("78-n", "Mystisches Bergmonster");
        p.put("78-a", "greift mit seinen riesigen Klauen nach<X>");
        p.put("79-n", "Räuber Schunkelbein");
        p.put("79-a", "überfällt<X>aus dem Hinterhalt");
        p.put("80-n", "DEATH SPELL");
        p.put("80-a", "speit glühende Funken auf<X>");
        p.put("81-n", "SCHWARZDRACHE");
        p.put("81-a", "speit Höllenfeuer gegen<X>");
        p.put("82-n", "RAH-NO-TEP-HEP");
        p.put("82-a", "stöhnt und greift sich<X>");
        p.put("83-n", "GEIST der *sieben* Monde");
        p.put("83-a", "lacht und stürzt sich auf<X>");
        p.put("84-n", "DEMON *Prinz*");
        p.put("84-a", "schwingt sein Knochenschwert gegen<X>");
        p.put("85-n", "Bananenfressendes Monster");
        p.put("85-a", "versucht<X>zu schälen");
        p.put("86-n", "Schlabbriges Gespenst");
        p.put("86-a", "buht<X>an");
        p.put("87-n", "Zombie");
        p.put("87-a", "sabbert auf<X>");
        p.put("88-n", "Manischer Wächter");
        p.put("88-a", "haut seine schwere Axt auf<X>");
        p.put("89-n", "*Brombadegs* Nachbar");
        p.put("89-a", "umschlingt<X>mit schleimigen Tentakeln");
        return p;
    }

}
