/*
 * Copyright Captainsoft 2010 - 2015.
 * All rights reserved.
 */
package com.captainsoft.tools.patch.en;

import java.util.HashMap;
import java.util.Map;

import com.captainsoft.tools.patch.PatchData;

/**
 * @author
 */
public class ItemPatchEnglish implements PatchData {

    public Map<String, String> data() {
        Map<String, String> p = new HashMap<String, String>();
        p.put("1", "Plant");
        p.put("2", "Plant");
        p.put("3", "Plant");
        p.put("4", "Plate");
        p.put("5", "Cup");
        p.put("6", "Kitchen Knife");
        p.put("7", "Tablecloth");
        p.put("8", "Tablecloth");
        p.put("9", "Candle");
        p.put("10", "Candle");
        p.put("11", "Strawberries");
        p.put("12", "Pizza Napoliano");
        p.put("13", "Cherries");
        p.put("14", "Banana");
        p.put("15", "Chocolate");
        p.put("16", "Nutcorner");
        p.put("17", "Donut");
        p.put("18", "Can of Soda");
        p.put("19", "Box of Peanuts");
        p.put("20", "Cup of Milk Coffee");
        p.put("21", "Pot of Milk Coffee");
        p.put("22", "Mana-Muesli-Bar");
        p.put("23", "Mana-Permanent-Candy");
        p.put("24", "Mana-Energy-Drink");
        p.put("25", "Candle");
        p.put("26", "Cloth");
        p.put("27", "Goblet");
        p.put("28", "Cnadlestick");
        p.put("29", "Little Cloth");
        p.put("30", "Fork");
        p.put("31", "Chocoloco Bar");
        p.put("32", "Justin Chamberlain Dolly");
        p.put("33", "Little Statue");
        p.put("34", "Deep Dungeon T-Shirt");
        p.put("35", "Dolly");
        p.put("36", "Dolly");
        p.put("37", "Precious Goblet");
        p.put("38", "Precious Statue");
        p.put("39", "Precious Bowl");
        p.put("40", "Precious Cross");
        p.put("41", "Precious Crown");
        p.put("42", "Precious Bracelets");
        p.put("43", "Precious Horseshoe");
        p.put("44", "Rags");
        p.put("45", "Dungeon Big Burger");
        p.put("46", "Garbage");
        p.put("47", "Can of Garbage");
        p.put("48", "Shards");
        p.put("49", "Rags");
        p.put("50", "Wakizashi");
        p.put("51", "Rapier");
        p.put("52", "Hunting Sword");
        p.put("53", "Massive Sword");
        p.put("54", "Sabre of the Pirates");
        p.put("55", "Katana");
        p.put("56", "Claymore");
        p.put("57", "Spiked Sword");
        p.put("58", "Lightning Sword");
        p.put("59", "Special Katana (+2)");
        p.put("60", "Snake Sword");
        p.put("61", "Ruby Sword");
        p.put("62", "Dragon Sword");
        p.put("63", "Skull Sabre");
        p.put("64", "Sword of the Ronin");
        p.put("65", "Sword of the Shaolin");
        p.put("66", "Battle Staff");
        p.put("67", "Sparklers");
        p.put("68", "Club");
        p.put("69", "Fighting Paddle");
        p.put("70", "Spear");
        p.put("71", "Halberd");
        p.put("72", "Trident");
        p.put("73", "Snake Spear");
        p.put("74", "Pike of Li Tai Peh");
        p.put("75", "Pike of the Masai");
        p.put("76", "Throwing Spurs");
        p.put("77", "Shortbow");
        p.put("78", "Boomerang");
        p.put("79", "Crossbow");
        p.put("80", "Bow of the Indians");
        p.put("81", "Ninja Stars");
        p.put("82", "Double Crossbow");
        p.put("83", "Tiger Bow");
        p.put("84", "Ghost Bow");
        p.put("85", "Jade Bow");
        p.put("86", "Tomahawk");
        p.put("87", "Double Axe");
        p.put("88", "Fighting Axe");
        p.put("89", "Vikings Axe");
        p.put("90", "Full Moon Axe");
        p.put("91", "Prism Sword");
        p.put("92", "Bone Sword");
        p.put("93", "Sword of Horns");
        p.put("94", "Fez");
        p.put("95", "Sable Cap");
        p.put("96", "Iron Helmet");
        p.put("97", "Taschko");
        p.put("98", "Chitin Helmet");
        p.put("99", "Knight Helmet");
        p.put("100", "Lion Mask");
        p.put("101", "Bone Helmet");
        p.put("102", "Helmet of Matawaloo");
        p.put("103", "Helmet of the Underworld");
        p.put("104", "Trenchcoat");
        p.put("105", "Iron Armor");
        p.put("106", "Samurai Armor");
        p.put("107", "Chitin Armor");
        p.put("108", "Knight Armor");
        p.put("109", "Lion Armor");
        p.put("110", "Bone Armor");
        p.put("111", "Uniform of  Miyamato");
        p.put("112", "Armor of the Underworld");
        p.put("113", "Jade Armor");
        p.put("114", "Pants");
        p.put("115", "Iron Armour");
        p.put("116", "Samurai Armour ");
        p.put("117", "Chitin Armour");
        p.put("118", "Lion Pants");
        p.put("119", "Knight Armor");
        p.put("120", "Bone Armor");
        p.put("121", "Uniform of Chen Chen");
        p.put("122", "Armor of the Underworld");
        p.put("123", "Jade Armor");
        p.put("124", "Cape of the Underworld");
        p.put("125", "Tiger Cape");
        p.put("126", "Jade Chain");
        p.put("127", "Jade Shield");
        p.put("128", "Bat Cape");
        p.put("129", "Chain of Moderam Soderam");
        p.put("130", "Samurai Chain");
        p.put("131", "Snake Chain");
        p.put("132", "Iron Shield");
        p.put("133", "Wood Shield");
        p.put("134", "Chitin Shield");
        p.put("135", "Jade Cape");
        p.put("136", "Tie");
        p.put("137", "T-Shirt XXL");
        p.put("138", "Gold Chain");
        p.put("139", "\"Mosquito Swarm\"");
        p.put("140", "\"Prism Missile\"");
        p.put("141", "\"The Sledgehammer\"");
        p.put("142", "\"Meteor Rain\"");
        p.put("143", "\"Magic Vampire Bite\"");
        p.put("144", "\"Tin Soldiers Attack!\"");
        p.put("145", "\"Hot Wax Cleaning\"");
        p.put("146", "\"Heat of the Sahara\"");
        p.put("147", "\"Vapor Cloud\"");
        p.put("148", "\"Bowling Attack\"");
        p.put("149", "\"Hot Stings of Stars\"");
        p.put("150", "\"Water Pearls\"");
        p.put("151", "\"Lightning\"");
        p.put("152", "\"Magnesium Rays\"");
        p.put("153", "\"Chinese Fireworks\"");
        p.put("154", "\"Atom Explosion\"");
        p.put("155", "\"Cholesterin Raise Attack\"");
        p.put("156", "\"Rainstorm\"");
        p.put("157", "\"Hail Storm\"");
        p.put("158", "\"Avalanche\"");
        p.put("159", "Shaolin Powder");
        p.put("160", "Slime Bombe");
        p.put("161", "Böller");
        p.put("162", "Lava Bomb");
        p.put("163", "Water Bomb");
        p.put("164", "Tomato Juice Bomb");
        p.put("165", "Pepper Bomb");
        p.put("166", "Stink Bomb");
        p.put("167", "Chili Coffee");
        p.put("168", "\"Bunga Terra Tissa Tu\"");
        p.put("169", "\"Spells\"");
        p.put("170", "\"Chemical Reactions\"");
        p.put("171", "\"Bombs and their Effect\"");
        p.put("172", "");
        p.put("173", "\"DeepDeep Dungeon Walkthrough\"");
        p.put("174", "\"Power Games\"");
        p.put("175", "");
        p.put("176", "Bucket");
        p.put("177", "Bucket full with Chili");
        p.put("178", "Piece of Wire");
        p.put("179", "Instant Coffee");
        p.put("180", "Heavy Gold Jewelry");
        p.put("181", "Voltmeter");
        p.put("182", "Ruler");
        p.put("183", "Pad");
        p.put("184", "Paperclip");
        p.put("185", "Image");
        p.put("186", "Plant");
        p.put("187", "Plant");
        p.put("188", "Garbage");
        p.put("189", "Pen");
        p.put("190", "Office Key");
        p.put("191", "Diamond Helmet");
        p.put("192", "");
        p.put("193", "Eyeballs of a Zombie");
        p.put("194", "Leg of a Zombie");
        p.put("195", "Arm of a Zombie");
        p.put("196", "Arm of a Zombie");
        p.put("197", "Leg of a Zombie");
        p.put("198", "Order List");
        p.put("199", "Key to the Dungeon");
        p.put("200", "Room Keys");
        p.put("201", "Shovel");
        p.put("202", "keys to the Side Entrance");
        p.put("203", "Green Key");
        p.put("204", "Motif");
        p.put("205", "Heavy Weight");
        p.put("206", "Keys to the Teleporter");
        p.put("207", "Purple Keys");
        p.put("208", "Key \"Experience\"");
        p.put("209", "Diamons Chain");
        p.put("210", "Gold Chain");
        p.put("211", "Chest Picklock");
        p.put("212", "Screwdriver");
        p.put("213", "Yellow Key");
        p.put("214", "Pliers");
        p.put("215", "Towle");
        p.put("216", "Rainbow Salt Shaker");
        p.put("217", "Candle");
        p.put("218", "Fish Bone");
        p.put("219", "Hot Chili Dish");
        p.put("220", "Code Wheel");
        p.put("221", "Egg of an Emu");
        p.put("222", "Bubble Gum Paper");
        p.put("223", "Pack of Gum");
        p.put("224", "Transit Visa");
        p.put("225", "Order from Bradfish");
        p.put("226", "Key from Ringring");
        p.put("227", "Nuko Comic");
        p.put("228", "Key from Wilbur");
        p.put("229", "Entrance Ticket");
        p.put("230", "Chair Leg");
        p.put("231", "Studio Key A");
        p.put("232", "Key to the inner Dungeon");
        p.put("233", "Key to Bungalow");
        p.put("234", "Cells Keychain");
        p.put("235", "Key to the Fan-Shop");
        p.put("236", "Lead Ammunition");
        p.put("237", "Sparkling Pearls");
        p.put("238", "Skull Key");
        p.put("239", "Quest-Request No 1");
        p.put("240", "Quest-Request No 2");
        p.put("241", "Quest-Request No 3");
        p.put("242", "Plasma Prism");
        p.put("243", "Red Keycard");
        p.put("244", "");
        p.put("245", "");
        p.put("246", "50 Chips");
        p.put("247", "40 Chips");
        p.put("248", "20 Chips");
        p.put("249", "30 Chips");
        p.put("250", "70 Chips");
        return p;
    }

}
