/*
 * Copyright Captainsoft 2010 - 2015.
 * All rights reserved.
 */
package com.captainsoft.tools.patch.en;

import java.util.HashMap;
import java.util.Map;

import com.captainsoft.tools.patch.PatchData;

/**
 * @author
 */
public class MonsterPatchEnglish implements PatchData {

    public Map<String, String> data() {
        Map<String, String> p = new HashMap<String, String>();
        p.put("1-n", "Eye on Legs");
        p.put("1-a", "hits<X>with its legs");
        p.put("2-n", "Slimy Gutworm");
        p.put("2-a", "spits on<X>with slimy spit");
        p.put("3-n", "Brain Drainer (from Hell)");
        p.put("3-a", "nabs after<X>");
        p.put("4-n", "Carpet of Torture");
        p.put("4-a", "bites<X>");
        p.put("5-n", "Flying Wurst Wacker");
        p.put("5-a", "splashes yukky juice on<X>");
        p.put("6-n", "The Evil T");
        p.put("6-a", "pounds on<X>'s head");
        p.put("7-n", "Fire spitting Pharynx");
        p.put("7-a", "heats against<X>");
        p.put("8-n", "The aggressive Cloud");
        p.put("8-a", "douches<X>cold");
        p.put("9-n", "Evil Spell");
        p.put("9-a", "bewiches<X>");
        p.put("10-n", "Stomactract Masticator");
        p.put("10-a", "clutches after<X>");
        p.put("11-n", "Mad Jumper");
        p.put("11-a", "jumps on<X>");
        p.put("12-n", "Mister Bombastic");
        p.put("12-a", "jostelst against<X>");
        p.put("13-n", "Sklett Warrior");
        p.put("13-a", "waves golden sabre against<X>");
        p.put("14-n", "Magician of the Mountains");
        p.put("14-a", "invokes fire rain on<X>");
        p.put("15-n", "Zipfel Stone");
        p.put("15-a", "prickels<X>");
        p.put("16-n", "Stone Monster");
        p.put("16-a", "boxes<X>");
        p.put("17-n", "Stone Monster General");
        p.put("17-a", "boxes<X>hard");
        p.put("18-n", "GIGANTUS");
        p.put("18-a", "smacks<X>with his flippers");
        p.put("19-n", "Robber");
        p.put("19-a", "mugs<X>");
        p.put("20-n", "Man Eating Tree");
        p.put("20-a", "snatches<X>with his bony limbs");
        p.put("21-n", "Magic Tree");
        p.put("21-a", "scatters magic powder upon<X>");
        p.put("22-n", "Carrot Chap");
        p.put("22-a", "bangs his beet against<X>");
        p.put("23-n", "Spud Monster");
        p.put("23-a", "mases on<X>");
        p.put("24-n", "Flesh Eating Plant");
        p.put("24-a", "gobbles around<X>");
        p.put("25-n", "Titan Toad");
        p.put("25-a", "twines tongue around<X>");
        p.put("26-n", "Soured Gherkin");
        p.put("26-a", "gives<X>the evil eye");
        p.put("27-n", "Mountain Monster");
        p.put("27-a", "gropes at<X>");
        p.put("28-n", "Vulture");
        p.put("28-a", "hurls down on<X>");
        p.put("29-n", "Thunderstorm");
        p.put("29-a", "throws flashes at<X>");
        p.put("30-n", "Malicious Comic Book");
        p.put("30-a", "hits<X>with sharp pages");
        p.put("31-n", "Wizard");
        p.put("31-a", "aims evil powers against<X>");
        p.put("32-n", "Spook");
        p.put("32-a", "scares<X>");
        p.put("33-n", "Vampire");
        p.put("33-a", "nibbles at<X>");
        p.put("34-n", "Bat");
        p.put("34-a", "sways against<X>");
        p.put("35-n", "Earth Worm");
        p.put("35-a", "sucks at<X>");
        p.put("36-n", "Dark Watcher");
        p.put("36-a", "throws his axe against<X>");
        p.put("37-n", "Prawn Pronk Monk");
        p.put("37-a", "wobbles his tentacles against<X>");
        p.put("38-n", "Mutantor");
        p.put("38-a", "clings on<X>");
        p.put("39-n", "Spongy Eyes");
        p.put("39-a", "spatters against<X>");
        p.put("40-n", "Ice Star");
        p.put("40-a", "freezes<X>");
        p.put("41-n", "Gnome from Zürich");
        p.put("41-a", "picks on<X>");
        p.put("42-n", "Mildewman");
        p.put("42-a", "stinks against<X>");
        p.put("43-n", "Spider");
        p.put("43-a", "pinches<X>");
        p.put("44-n", "Floor Slime");
        p.put("44-a", "muds<X>");
        p.put("45-n", "Sheet Ghost");
        p.put("45-a", "screams at<X>");
        p.put("46-n", "Tentacle");
        p.put("46-a", "gums on<X>");
        p.put("47-n", "Horns Buck");
        p.put("47-a", "barges against<X>");
        p.put("48-n", "Dungeon Rat");
        p.put("48-a", "gnaws at<X>");
        p.put("49-n", "Fire Skull");
        p.put("49-a", "fries<X>");
        p.put("50-n", "Lip Lipp");
        p.put("50-a", "swipes at<X>");
        p.put("51-n", "CANRABBONGO");
        p.put("51-a", "scratches<X>");
        p.put("52-n", "Magic Bolt");
        p.put("52-a", "fires magic glitter on<X>");
        p.put("53-n", "Skeleton Warrior");
        p.put("53-a", "sabres against<X>");
        p.put("54-n", "Fire Wizard");
        p.put("54-a", "throws flame at<X>");
        p.put("55-n", "Giant Demon");
        p.put("55-a", "claws<X>");
        p.put("56-n", "Recycl-Clohr");
        p.put("56-a", "twirls<X>");
        p.put("57-n", "Killer Tomato");
        p.put("57-a", "squeezes<X>");
        p.put("58-n", "Mummy");
        p.put("58-a", "reaches after<X>");
        p.put("59-n", "Dungeon Master");
        p.put("59-a", "mashes on<X>");
        p.put("60-n", "Rheumaster");
        p.put("60-a", "pours waterfalls on<X>");
        p.put("61-n", "Rheumatism Element");
        p.put("61-a", "catches a cold against<X>");
        p.put("62-n", "Trick Chest");
        p.put("62-a", "snaps at<X>");
        p.put("63-n", "Dragon");
        p.put("63-a", "fires<X>up");
        p.put("64-n", "Skkizzor");
        p.put("64-a", "aims its scissor hand at<X>");
        p.put("65-n", "Beholder");
        p.put("65-a", "smacks at<X>");
        p.put("66-n", "Fire Pickler");
        p.put("66-a", "knackers at<X>");
        p.put("67-n", "Giant Tarantula");
        p.put("67-a", "bites<X>");
        p.put("68-n", "Zombie");
        p.put("68-a", "throws brain mass on<X>");
        p.put("69-n", "Drooling Zombie");
        p.put("69-a", "wets upon<X>");
        p.put("70-n", "Zombie Salesman");
        p.put("70-a", "pushes<X>");
        p.put("71-n", "Zombie Mutant");
        p.put("71-a", "scoofs<X>");
        p.put("72-n", "Zombie Guard");
        p.put("72-a", "clamps<X>");
        p.put("73-n", "Zombie Janitor");
        p.put("73-a", "waddles the mop against<X>");
        p.put("74-n", "Paranoid Potted Plan");
        p.put("74-a", "twines after<X>");
        p.put("75-n", "Zombie Secretary");
        p.put("75-a", "throws office supplies against<X>");
        p.put("76-n", "Fire Mushroom");
        p.put("76-a", "is hot on<X>");
        p.put("77-n", "Mildew");
        p.put("77-a", "molds against<X>");
        p.put("78-n", "Mystig Mountain Nature");
        p.put("78-a", "grasps with its heavy claws after<X>");
        p.put("79-n", "Bandit Seesawleg");
        p.put("79-a", "hijacks<X>from the ambush");
        p.put("80-n", "DEATH SPELL");
        p.put("80-a", "spews hot sparkles at<X>");
        p.put("81-n", "BLACK DRAGON");
        p.put("81-a", "belches hot breath against<X>");
        p.put("82-n", "RAH-NO-TEP-HEP");
        p.put("82-a", "moans and grasps<X>");
        p.put("83-n", "GHOST OF NINE WEEKS");
        p.put("83-a", "cackles and storms at<X>");
        p.put("84-n", "DEMON LORD");
        p.put("84-a", "spins his bone sword against<X>");
        p.put("85-n", "Banana Eating Mamal");
        p.put("85-a", "tries to peel<X>");
        p.put("86-n", "Baggy Ghost");
        p.put("86-a", "boos at<X>");
        p.put("87-n", "Zombie");
        p.put("87-a", "slobbers on<X>");
        p.put("88-n", "Maniac Guardian");
        p.put("88-a", "hurls his heavy axe on<X>");
        p.put("89-n", "*Brombadegs* Neighbor");
        p.put("89-a", "entwines<X>with slimy tentacles");
        return p;
    }

}
